Server: user and auth modules
AliceNov/BookReviews-project pull request #1
Opened 2022-01-31 14:32 UTC by AliceNov

Добавлены модули юзер и аутентификация на сервере. Созданы роли: admin и user. Также реализовано хэширование паролей с помощью bcrypt.

2022-01-31 14:39 UTC, cyclist-nn requested changes

2022-01-31 14:39 UTC, cyclist-nn commented on api/.eslintrc.js
> +module.exports = {
возьми лучше конфиг из ангуляр версии, если там что то будет сильно конфликтовать то убери

2022-01-31 14:39 UTC, cyclist-nn commented on api/.prettierrc
> +{
не надо претир, мы от него отказались

2022-01-31 14:39 UTC, cyclist-nn commented on api/src/user/controller/user.controller.ts
> +    create(@Body()user: User): Observable<User | Object> {
<User | Object> как то вот это не очень, почему он не юзера то может вернуть?

2022-01-31 14:39 UTC, cyclist-nn commented on api/src/user/controller/user.controller.ts
> +    login(@Body() user: User): Observable<Object> {
тут тоже почему Object

2022-01-31 14:39 UTC, cyclist-nn commented on api/src/user/controller/user.controller.ts
> +    deleteOne(@Param('id')id: string): Observable<any> {
почему any

2022-01-31 15:10 UTC, AliceNov commented on api/src/user/controller/user.controller.ts
> +    login(@Body() user: User): Observable<Object> {
тут Object тк возвращает {access_token: jwt}

2022-01-31 15:13 UTC, cyclist-nn commented on api/src/user/controller/user.controller.ts
> +    login(@Body() user: User): Observable<Object> {
ну так это не Object, а {access_token: jwt}
Object это когда неизвестно что

2022-01-31 15:15 UTC, AliceNov commented on api/src/user/controller/user.controller.ts
> +    login(@Body() user: User): Observable<Object> {
Поняла, переделаю

2022-01-31 15:15 UTC, AliceNov commented on api/src/user/controller/user.controller.ts
> +    login(@Body() user: User): Observable<Object> {
Поняла, переделаю

2022-01-31 15:16 UTC, AliceNov commented on api/src/user/controller/user.controller.ts
> +    login(@Body() user: User): Observable<Object> {
Поняла, переделаю

2022-02-01 06:22 UTC, cyclist-nn commented on api/src/user/controller/user.controller.ts
> +    login(@Body() user: User): Observable<Object> {
точнее  {access_token: string}

2022-02-01 11:28 UTC, merged